### PR TITLE
Remove `run_constrained` requirements

### LINKED ISSUE #49: boost-cpp 1.70 is making conda solve 70x slower
I think that the problem is related to this: `conda` solver is unable to prune versions, because it won't find a satisfiable `boost-cpp` version.

Things needed to reproduce the problem are here:

https://gist.github.com/tadeu/49c6de435dae6764f6616eb10efde2a4

(this could also be a `conda` problem, instead of a particular problem in `boost-cpp`)

The diff for `conda env update --debug`, with both Boost versions, is here:

https://gist.github.com/tadeu/49c6de435dae6764f6616eb10efde2a4/revisions#diff-8c6e71389c61ffe86203031a361d8c00

Note that around line 563, it prunes all `boost-cpp` down to `0`

```
DEBUG conda.resolve:filter_group(400): boost: pruned from 122 -> 1
DEBUG conda.resolve:filter_group(400): boost-cpp: pruned from 39 -> 0
```

### PR DESCRIPTION
**Pull request by tadeu**
as it is affecting version pruning during conda solve, slowing it down a lot.

Fixes #49

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tadeu** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
Strong -1 on this. The constraint is here to prevent crashes that occur when defaults `libboost` is installed. This have been really annoying and occurred in numerous occasions with users unable to find the source of the problem.

**Comment by tadeu** [comment]
Sorry, in the original issue, I wrote that it was because of this that `conda solve` was slowing down a lot, but it was the result of a bad test here on my side. I still don't know what is the cause, and I've edited the issue. Anyway, it would be nice to have more documentation (some comments?) on why that constraint is necessary.

I didn't find a `libboost` package in `conda` or `conda-forge`. Is it ok to remove it?

**Comment by xhochy** [comment]
@tadeu it's on `anaconda` or `defaults` (same thing but people know it by different names). It has similar content as boost-cpp and when both are installed, conda-forge packages that use boost-cpp will run into segmententation faults.

**Comment by tadeu** [comment]
Yes, just saw that, thanks!

**Comment by xhochy** [comment]
Optimal solution would be to tackle https://github.com/conda-forge/boost-cpp-feedstock/issues/25 or sync the anaconda recipe to conda-forge.

**Pull request closed without merging**
