### PR TITLE
system layout for windows

### PR DESCRIPTION
**Pull request by isuruf**
Leaving this here for comments. @jschueller, @jakirkham, @bluescarni what do you think?

### CODE REVIEW

**Comment by bluescarni** [comment]
I like the idea in principle, as I am used to simple library names on linux and everything usually "just works" :)

I read yesterday that the naming changes in Boost 1.66 are supposed to make it easier to use the libraries in a multi-arch setup (e.g., compiling in 32 and 64 bit mode in Windows), but I assume this use case is not interesting for conda.

So it's a 👍 from my side.

Happy holidays everyone!

**Comment by bluescarni** [comment]
It looks like on appveyor the Python 3.6 build is not enabled. Is this intended?

**Comment by jschueller** [comment]
Yes, we need only one vc14 build.

**Comment by bluescarni** [comment]
Ah right, I always forget it.

**Comment by jakirkham** [comment]
Sounds like a good idea. Probably should do the same with Boost Python.

Could have trouble if there are other Boost libraries on the path though. Can’t say there is a different story for any other libraries in `conda- forge`.

Is it worth testing with a few packages?

**Comment by jakirkham** [comment]
We may want to pull older packages of the same version if we do this.

**Comment by isuruf** [comment]
> Is it worth testing with a few packages?

Sure. I don't think any conda-forge package is built with 1.66 yet. If so, we can merge this and test.

**Pull request merged**
