### PR TITLE
Add `run_exports` to `boost-cpp`

### PR DESCRIPTION
**Pull request by jakirkham**
Pin all the way to the patch level as they include the patch version in the SONAME.

https://abi-laboratory.pro/index.php?view=timeline&l=boost

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @conda-forge/core (for awareness)
cc @kkraus14

**Comment by beckermr** [comment]
how did we not have this before?

Also, we should eventually remove the `pin_run_as_build` in the pinnings file once we have enough versions of this done with the constraint.

**Comment by kkraus14** [comment]
Just a note, a good portion of `boost-cpp` is header only that is not needed at runtime, certain modules like `boost::filesystem` are not which means a binary component is needed at runtime. I'm not sure what the typical path for conda-forge is in these situations as to whether the run export should be opt-in or opt-out.

**Comment by scopatz** [comment]
@kkraus14 - in that case, there is a mechanism to avoid run-exports in the deps that need/want to

**Comment by jakirkham** [comment]
It's a great question, Matt. Was also surprised. In any event, this should fix it 🙂

Yeah there's [`ignore_run_exports`]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements ) for skipping the pinning downstream.

**Comment by beckermr** [comment]
Right. Downstreams can skip things. We could also further subdivide the boost package, making the header only parts a separate output and dep of boost-cpp.

**Comment by beckermr** [comment]
> Also, we should eventually remove the pin_run_as_build in the pinnings file once we have enough versions of this done with the constraint.

We could ship a repodata patch if we wanted to remove that now. I am agnostic on that.

**Review by isuruf — CHANGES_REQUESTED** [review]
We had a big discussion of not using `run_exports` in boost-cpp. I can't find the discussion right now.

Until all the recipes in conda-forge which use headers only are fixed with `ignore_run_exports`, -1 from me. If you can do the leg work to fix all the recipes before merging this, I'm okay with this.

**Comment by beckermr** [comment]
> We had a big discussion of not using run_exports in boost-cpp. I can't find the discussion right now.

Ahh ok. I didn't know about that until now. If you can find the text of it, I'd love to read to catch up. 

In the meantime, maybe @jakirkham we should comment out the run export in the recipe and leave a comment on the underlying issues and steps needed to resolve them? This way newcomers don't have to backtrack and ultimately rely on the memories of ppl watching PRs to get it right.

**Comment by jakirkham** [comment]
I'd rather just leave the PR open instead of merging with a comment. It didn't take us long to find the issue. Plus this makes it clear that this work still needs to be done. If there's relevant conversation, we can track it here as well.

**Comment by h-vetinari** [comment]
> Until all the recipes in conda-forge which use headers only are fixed with `ignore_run_exports`, -1 from me. If you can do the leg work to fix all the recipes before merging this, I'm okay with this.

How about we solve this with a separate output rather than requiring recipes which only need header-only boost to add the right `ignore_run_exports` - the latter is IMO way less obvious and more error-prone.

In contrast, if a recipe declares a host-dependence on (say) `libboost-header-only`, then it would be apparent at first sight what that recipe is claiming to rely on, and why that wouldn't result in a run-export.

(yes, I'm thinking about _eventually_ [renaming](https://github.com/conda-forge/conda-forge.github.io/issues/1073) `boost-cpp` -> `libboost`, and would be willing to do the legwork; it's <100 dependent feedstocks, so it's feasible with a bit of time)

**Comment by h-vetinari** [comment]
> Why not just add `boost-hpp` for the headers and use that? `boost-cpp` could depend on it.

Do I understand correctly that you think an additional header-only output is worth considering? The naming discussion can come after ;)

(I personally find boost-cpp & boost-hpp too close for comfort - plus the lib-prefix would be nice to have uniformly - but I agree "hpp" is a neat idea.)

**Comment by isuruf** [comment]
AnacondaRecipes/boost-cpp-feedstock have all of these. What we have to do is to sync this recipe with that.
Only major thing we have to do is to write a migrator to go from `boost-cpp` -> `libboost` or `boost-headers` depending on if `run` had `boost-cpp` or not.

**Comment by h-vetinari** [comment]
> Nvm. there's no `boost-headers` or something similar there.

Yeah, from what I could tell, boost-cpp only [has one](https://github.com/conda-forge/boost-cpp-feedstock/blob/main/recipe/meta.yaml) output (and the boost feedstock [is for](https://github.com/conda-forge/boost-feedstock/blob/main/recipe/meta.yaml) the python bindings based on boost-cpp).

AnacondaRecipes using `libboost` is actually another good argument for doing the rename...

> Only major thing we have to do is to write a migrator to go from `boost-cpp` -> `libboost` or `boost-headers` depending on if `run` had `boost-cpp` or not.

Might be a good exercise to do that (not sure how much effort it is to write a custom migrator), but based on the experience from smaller-scale renames with abseil & grpc, it would be possible to:
* add libboost (keeping boost-cpp as a compat output)
* migrate both outputs to a new version
* work through the feedstocks to ensure they all use the new output [<- if the migrator isn't feasible, I'd be willing to do that]
* remove the compat output eventually

**Comment by h-vetinari** [comment]
> AnacondaRecipes/boost-feedstock have all of these.

I had misinterpreted this as an "OR", but in any case, https://github.com/AnacondaRecipes/boost-feedstock does both the lib and the python bindings. The names are different from ours also for the python bindings:

| | conda-forge | Anaconda |
|-|-|-|
| lib | boost-cpp | libboost | 
| header-only lib | - | - |
| python bindings | boost | py-boost |

**Comment by jakirkham** [comment]
> > Why not just add `boost-hpp` for the headers and use that? `boost-cpp` could depend on it.
> 
> 
> 
> Do I understand correctly that you think an additional header-only output is worth considering?

Yes

**Comment by h-vetinari** [comment]
> @isuruf: Only major thing we have to do is to write a migrator to go from `boost-cpp` -> `libboost` or `boost-headers` depending on if `run` had `boost-cpp` or not.

I opened an issue to coordinate how to actually do this: https://github.com/conda-forge/boost-cpp-feedstock/issues/137

**Comment by h-vetinari** [comment]
> Only major thing we have to do is to write a migrator to go from `boost-cpp` -> `libboost` or `boost-headers` depending on if `run` had `boost-cpp` or not.

There's now a functioning draft for this: https://github.com/regro/cf-scripts/pull/1668

**Comment by h-vetinari** [comment]
This has been done in https://github.com/conda-forge/boost-feedstock/pull/164, closing this

**Comment by jakirkham** [comment]
Thanks Axel! 🙏

**Pull request closed without merging**
