### PR TITLE
Rebuild 1.78 with newer compilers

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render

**Comment by isuruf** [comment]
If there is indeed an ABI breakage, then rebuilding will break older packages. So we should not merge it and investigate more.

**Review by varlackc — COMMENTED** [review]
There seem to be some conflicts in the current branch. 

   Also, it might be a good idea to modify the `home` url to use `https` instead of `http`

   In addition, we might want to add a `dev_url` and `doc_url`

**Comment by h-vetinari** [comment]
We now have 1.82 and will migrate to that soon. All other changes need to happen on https://github.com/conda-forge/boost-feedstock now.

**Pull request closed without merging**
