### PR TITLE
Update to 1.64

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by isuruf** [comment]
Looks good to me. 
Should we do https://github.com/conda-forge/boost-cpp-feedstock/issues/8. I'm asking only because we can do that only in a version bump.

**Comment by jschueller** [comment]
@isuruf is that ok ?

**Comment by isuruf** [comment]
Yes, looks good. Line 91-96 of meta.yaml would have to be changed.
@conda-forge/boost-cpp what do you think about this change?

**Comment by jschueller** [comment]
win_vstr would be empty ?

**Comment by isuruf** [comment]
It seems on windows, boost enables auto-linking with msvc and therefore linking will fail unless we have `-DBOOST_ALL_NO_LIB`. http://stackoverflow.com/questions/2458637/boost-link-error-when-using-layout-system-on-vs2005

Sorry for bothering you with this. Let's remove the last commit.

**Pull request merged**
