### PR TITLE
Update to 1.74

### PR DESCRIPTION
**Pull request by jschueller**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by xhochy** [comment]
Can we use the chance and introduce a `run_exports`?

**Comment by isuruf** [comment]
Are you willing to fix all the recipes that use headers only to add `ignore_run_exports`?

**Comment by xhochy** [comment]
We already need `ignore_run_as_build` in the header-only case, e.g. I needed to use it here: https://github.com/conda-forge/arrow-cpp-feedstock/blob/5e7918ed76455ddd868675e4ef6a917aa6f355e9/recipe/meta.yaml#L54

We already set `pin_run_as_build` in our pinnings: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/3de397bdab258950a2932ccb68841786269397a2/recipe/conda_build_config.yaml#L160-L163

**Comment by isuruf** [comment]
> We already need ignore_run_as_build in the header-only case, e.g. I needed to use it here: https://github.com/conda-forge/arrow-cpp-feedstock/blob/5e7918ed76455ddd868675e4ef6a917aa6f355e9/recipe/meta.yaml#L54

It's not needed AFAIK.

> We already set pin_run_as_build in our pinnings: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/3de397bdab258950a2932ccb68841786269397a2/recipe/conda_build_config.yaml#L160-L163

That only applies if `boost-cpp` is in `run`

**Review by xhochy — APPROVED** [review]

**Comment by xhochy** [comment]
> > We already set pin_run_as_build in our pinnings: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/3de397bdab258950a2932ccb68841786269397a2/recipe/conda_build_config.yaml#L160-L163
> 
> That only applies if `boost-cpp` is in `run`

Makes sense, I'll investigate in detail what is going on there.

**Comment by jakirkham** [comment]
macOS didn't run on `master` so packages were not uploaded. Restarted the build.

**Pull request merged**
