### PR TITLE
boost-cpp v1.81.0

### PR DESCRIPTION
**Pull request by sdebionne**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sdebionne** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks for the PR Samuel! 🙏

Generally this seems reasonable

As noted in comment ( https://github.com/conda-forge/boost-cpp-feedstock/pull/133#issuecomment-1396688046 ), am going to give the bot a little more time to see if we fixed the issue with autoupdate PRs

Though will merge this later today in either case

**Comment by sdebionne** [comment]
@jakirkham Any chance that this PR could be merged?

**Comment by jakirkham** [comment]
Ah sorry for letting this slip. Yes. Thanks Samuel and Julien!

**Pull request merged**
