### PR TITLE
Move cmake

### PR DESCRIPTION
**Pull request by microe**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This pull request addresses issue #61 where the installed boost cmake config files were inhibiting the ability to link with the shared libraries of a dependent project. This change moves the ```[$PREFIX/lib,%LIBRARY_LIB]/cmake``` directory to ```cmake-bak```.

### CODE REVIEW

**Comment by xhochy** [comment]
Instead of moving the CMake files away, couldn't you simply set `Boost_NO_BOOST_CMAKE=ON`. The Boost CMake setup is quite new and thus explicitly has the option to turn it off and use the CMake provided `FindBoost.cmake`.

**Comment by microe** [comment]
Is this for building boost with build.sh/bld.bat or for building a dependent project? I'm happy to test and either update or close the PR.

**Comment by microe** [comment]
I looked this up and it looks like this is for building dependent projects. There are also many search engine hits that recommend using this variable as "on" because the Cmake config for boost is mostly broken. My PR disables this config and so it keeps people from having to frustratingly figure this out for themselves. Whenever the boost devs get the Cmake config straightened out, this feature of the package can always be brought back.

**Comment by jschueller** [comment]
boost provided cmake config files are fine these days, closing

**Pull request closed without merging**
