### PR TITLE
1.72: ARM OSX Migrator

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
I'd rather that we use 1.73 in the pinning file for arm64

**Comment by xhochy** [comment]
> I'd rather that we use 1.73 in the pinning file for arm64

What's the reasoning for that? I quite dislike different pinnings for different arches.

**Comment by jakirkham** [comment]
I think we also agreed to do every other version of Boost. So following that we wouldn't do 1.73, but do 1.72 and 1.74.

**Comment by isuruf** [comment]
Reasoning is that we don't want to support older software for a new platform. Older software might or might not work, but nobody is trying to use older software except us.

**Comment by xhochy** [comment]
https://github.com/conda-forge/boost-cpp-feedstock/pull/81 nicely resolves this :)

**Comment by jakirkham** [comment]
Yeah jumping to the the next version makes sense.

Understood, but this is how we have decided to handle Boost. So we should try to do it consistently. Or revisit how we handle Boost 🙂

**Pull request merged**
